const express = require('express')
const router = express.Router()
const home = require('./modules/home')
const admin = require('./modules/admin')
const user = require('./modules/user')
const item = require('./modules/item')
const record = require('./modules/record')
const instrument = require('./modules/instrument')
const labelPrint = require('./modules/labelPrint')
const { generalErrorHandler } = require('../middleware/error-handler')
const { authenticated } = require('../middleware/auth')
const { authenticatedAdmin } = require('../middleware/auth')
const alertNotice = require('./modules/notice')

router.use('/alertNotice', authenticated,alertNotice)
router.use('/labelPrint', authenticated, labelPrint)
router.use('/instrument', authenticated, instrument)
router.use('/item', authenticated, item)
router.use('/record', authenticated, record)
router.use('/admin', authenticatedAdmin, admin)
router.use('/users', user)
router.use('/', home)
router.use('/', generalErrorHandler)

module.exports = router